name: Build 

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
  
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - uses: actions/checkout@v4

      - name: Install-Package MSBuildTasks
        run: nuget install MSBuildTasks -Version 1.5.0.235

      - name: Restore Packages
        run: |
          nuget restore ConnectorFramework.sln
          nuget restore dotnet-connector\DotNetConnectors.sln
          nuget restore powershell-connector\PowerShellConnector.sln
          
      - name: Build solution
        run: |
          msbuild ConnectorFramework.sln -t:rebuild -property:Configuration=Release /p:ZipRelease=true /p:ProductName=OpenICF.Net
          msbuild dotnet-connector\DotNetConnectors.sln -t:rebuild -property:Configuration=Release /p:ZipRelease=true /p:ProductName=OpenICF.Net
          msbuild powershell-connector\PowerShellConnector.sln -t:rebuild -property:Configuration=Release /p:ZipRelease=true /p:ProductName=OpenICF.Net
