name: Build 

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
  
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - uses: actions/checkout@v4

      - name: Install-Package MSBuildTasks
        run: |
          nuget install MSBuildTasks -Version 1.5.0.235

      - name: Build ConnectorFramework.sln
        run: |
          nuget restore ConnectorFramework.sln
          msbuild ConnectorFramework.sln -property:Configuration=Release /p:ZipRelease=true /p:ProductName=OpenICF.Net
          set OPENICF_HOME=%cd%\FrameworkServer 
          dir env:

      - name: Build dotnet-connector\DotNetConnectors.sln
        run: |
          nuget restore dotnet-connector\DotNetConnectors.sln
          msbuild dotnet-connector\DotNetConnectors.sln -property:Configuration=Release /p:ZipRelease=true /p:ProductName=OpenICF.Net

      - name: Build powershell-connector\PowerShellConnector.sln
        run: |
          nuget restore powershell-connector\PowerShellConnector.sln
          msbuild powershell-connector\PowerShellConnector.sln -property:Configuration=Release /p:ZipRelease=true /p:ProductName=OpenICF.Net


